#!/usr/bin/env python3
"""
Script to post a specific tweet to X (Twitter) using the Teen Civics account.
This uses the existing twitter_publisher module.
"""

import os
import sys
from dotenv import load_dotenv

# Add src to path to import modules
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'src'))

# Load environment variables
load_dotenv()

from src.publishers.twitter_publisher import post_tweet

def main():
    # The tweet text generated by the summarizer
    tweet_text = "House bill proposes 2026 funding for Commerce, Justice, Science agencies. Includes major allocations for law enforcement, NASA, and NSF, with numerous policy restrictions."
    
    print(f"Preparing to post tweet: {tweet_text}")
    print(f"Tweet length: {len(tweet_text)}/280 characters")
    
    # Post the tweet
    success = post_tweet(tweet_text)
    
    if success:
        print("✅ Tweet posted successfully to @TeenCivics!")
    else:
        print("❌ Failed to post tweet")
        sys.exit(1)

if __name__ == "__main__":
    main()