import sys
import os
import logging

# Add project root to path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from dotenv import load_dotenv
load_dotenv()

# Configure logging to see output
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# Import the actual function from orchestrator to verify it works
from src.orchestrator import post_to_substack

def test_real_content():
    # This simulates the exact text format generated by format_bill_tweet
    # Using a sample bill that might be relevant to teens
    real_tweet_text = (
        "🏛️ Today in Congress\n\n"
        "The \"Youth Voting Rights Act\" (H.R. 5678) would expand voter registration access at public colleges and allow pre-registration for 16-year-olds nationwide.\n\n"
        "👉 See how this affects you: https://teencivics.org/bill/hr5678-119"
    )
    
    # A dummy tweet URL for testing
    real_tweet_url = "https://x.com/TeenCivics/status/1861555555555"
    
    print("----------------------------------------------------------------")
    print("Testing post_to_substack with realistic content...")
    print("----------------------------------------------------------------")
    print(f"Content:\n{real_tweet_text}")
    print(f"URL: {real_tweet_url}")
    print("----------------------------------------------------------------")
    
    success = post_to_substack(real_tweet_text, real_tweet_url)
    
    if success:
        print("\n✅ Success! The function in src/orchestrator.py is working correctly.")
        print("Check your Substack Notes to see how the formatting looks with emojis and links.")
    else:
        print("\n❌ Failed to post.")

if __name__ == "__main__":
    test_real_content()
