name: Test Orchestrator Fix

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: github-actions-fix

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Orchestrator in Test Mode
        env:
          CONGRESS_API_KEY: ${{ secrets.CONGRESS_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TESTING: false
          STRICT_POSTING: false
        run: python src/orchestrator.py --test-mode

      - name: Upload Test Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: orchestrator-test-logs
          path: /tmp/teencivics-test.log
